var GAME_LEVELS = [
  ["                                                                                ",
   "                                    xxxxxxxxxxxxxxxxxxxxxxx?                    ",
   "                                    xo                                          ",
   "                                    x                                           ",
   "                               xxxxxxxxxxx                                      ",
   "                                o                                               ",
   "               o                o                                               ",
   "               o                o                ooo                            ",
   "               o                                  o                             ",
   "               o                                 ooo                            ",
   "                                                  o                             ",
   "                                  xx                       xxxxxxxxxxxxx     x  ",
   "  x                               xx                                       o x  ",
   "  x                               xx                                       x x  ",
   "  x        oo                     xxxxxxxxxxxxxxxxxxxx                       x  ",
   "  x       xxxx                    x=    =x    oo                             x  ",
   "  x  @    x  x                  o xxxxxxxx oo    oo                  oo     ox  ",
   "  xxxFxxxxxxxxxjxxxxxxxxxxxxxxxxoxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxx  ",
   "                              x!o!x                  x               x          ",
   "                              x!o!x                  xj!!!!!!!!!!!!!!x          ",
   "                              x!o!x                  x!!!!!!!!!!!!!!!x          ",
   "                              x!o!x                  xxxxxxxxxxxxxxxxx          ",
   "                              x!?!x                                             ",
   "                              xxxxx                                             "],


  ["              xxxxxx                                                           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "x             x!!!!x                      vxxxv                                  x?xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x              xxx                        xxxxx                                                                   ",
   "x            xx!??xxxxxxxxxxxx!xxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxx                            ",
   "x            x                                                                                                    ",
   "x  o     o   x                                                                                          !!  !     ",
   "x            x                                                               o    o                     !!  !     ",
   "xF    o      x    xxx!!xxx        xxxxxxx   o                                                           !  !!     ",
   "x     =      x    xxxxxxxx         v   v          xxxxx                 xxxxxxxxxxxxxxxxxx              !  !!     ",
   "x  o     o   x    xxxxxxxx                         v v                  xv v v v v v v vxx                   xx  x",
   "x            x    xxxxxxxx                                              x               xx                   xx ox",
   "?jjjjjjjjjjjjj    xxxxxxxx           o              o                   x               xx                   xxo x",
   "                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               xx                   xx ox",
   "@                 x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxv v v v v               xx                   xx?xx",
   "xxxxxxxxxxxxxxx??xx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        xxxxx !!!!xxx!!!!xx?xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],






  ["??????????????????????????????????????????????????????????????????????????????????????????????????????????????",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                            ooooo @                                                            ",
   "                                          oo xxxxxxxxx                                  =                     ",
   "                =                        xxxxxxxxxxxxxxxx                                                     ",
   "                                         xxxxxxxxxxxxxxxxx                                                    ",
   "                                       = xxxxxxxxxxxxxxxxx                                                    ",
   "                                          xxxxxxxxxxxxxxx                =                                    ",
   "                                             xxxxxxxxx                                                        ",
   "                              ox             !!!!!!!!!                                                       ",
   "                             xxxxx                                                                            ",
   "  =                            x                                                                =             ",
   "                         o                                                                                    ",
   "                     oo                                                                                       ",
   "             xxxxxxxxxooo                                                                        =            ",
   "          xxxxxxxxxxxxxxxo                                                                                    ",
   "         xxxxxxxxxxxxxxxxx            o =                                                                     ",
   "         xxxxxxxxxxxxxxxxx                         xx                                                         ",
   "          xxxxxxxxxxxxxx        o                                                                             ",
   "            xxxxxxxxxx          x           o                                                                 ",
   "            !!!!!!!!!!                      x                                 xxxoooo                         ",
   "                                                            x              xxxxxxxxxxxx                       ",
   "                                      x                                   xxxxxxxxxxxxx o   =                 ",
   "             =                                                           xxxxxxxxxxxxxxxx                     ",
   "                                                                x       xxxxxxxxxxxxxxx                       ",
   "                                                                 x        xxxxxxxxxxx     o=                  ",
   "                                                                  xx       !!!xx!!!!                         ",
   "                                              o                                                               ",
   "                                     =                              =                                         ",
   "                                                                  =                       o                   ",
   "  =              =                     xx                                                                     ",
   "                                       xx                             =                                       ",
   "                                       xx                                                                     ",
   "                           xxxxxxxxxxxxxx    xj                                                               ",
   "       =                o  x   v  v  v  v  v  x                                                               ",
   "                       o   x                  x         xx                                                    ",
   "                      o    x                  x                                                               ",
   "                           x                  x               xx                                              ",
   "                =          x                  x                                       o                       ",
   "                           x!!!!!!!!!!!!!!!!!!x                      xx               xxxx                    ",
   "       o                   x!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!??xx!!xxxxx    o               ",
   "xxxxFxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
